name: Build Docker Image

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  ALLOY_CONTAINER_NAME: grafana-alloy
  REGISTRY_HOST: registry.cn-hangzhou.aliyuncs.com
  REGISTRY_USERNAME_ARM: originx

jobs:
  build-image:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            arch: amd64
    runs-on: ${{ matrix.os }}
    outputs:
      IMAGE_TAG_NAME: ${{ steps.build-image.outputs.IMAGE_TAG_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Generate image metadata
        id: build-image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          echo "IMAGE_TAG_NAME=${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}" >> "$GITHUB_OUTPUT"
          echo "GRAFANA_ALLOY_FULL_TAG=${{ env.REGISTRY_HOST }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.ALLOY_CONTAINER_NAME }}:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}" >> $GITHUB_ENV
          echo "GRAFANA_ALLOY_FULL_TAG_ARM=${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_USERNAME_ARM }}/${{ env.ALLOY_CONTAINER_NAME }}:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}-arm" >> $GITHUB_ENV

      - name: Build grafana-alloy docker and push(AMD64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.GRAFANA_ALLOY_FULL_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build grafana-alloy docker image and push(ARM64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ env.GRAFANA_ALLOY_FULL_TAG_ARM }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
